version: 0.0
os: linux
files:
  - source: target/ticketingservice-1.0.1-RELEASE.war
    destination: /usr/javaapp
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
